<?php

/**
 * PluginUserLoginHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUserLoginHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUserLoginHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUserLoginHistory');
    }

  static public function writeLoginHistory(sfEvent $event)
  {
    $params = $event->getParameters();
    if(true === $params['authenticated'])
    {
      $history = new UserLoginHistory();
      $history->ip = getenv('HTTP_X_FORWARDED_FOR') ? getenv('HTTP_X_FORWARDED_FOR') : getenv('REMOTE_ADDR');
      $history->User = $event->getSubject()->getGuardUser();
      $history->save();
    }
  }
}
