<?php

/**
 * BaseUserLoginHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ip
 * @property string $state
 * @property integer $user_id
 * @property sfGuardUser $User
 * 
 * @method string           getIp()      Returns the current record's "ip" value
 * @method string           getState()   Returns the current record's "state" value
 * @method integer          getUserId()  Returns the current record's "user_id" value
 * @method sfGuardUser      getUser()    Returns the current record's "User" value
 * @method UserLoginHistory setIp()      Sets the current record's "ip" value
 * @method UserLoginHistory setState()   Sets the current record's "state" value
 * @method UserLoginHistory setUserId()  Sets the current record's "user_id" value
 * @method UserLoginHistory setUser()    Sets the current record's "User" value
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserLoginHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_login_history');
        $this->hasColumn('ip', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('state', 'string', 6, array(
             'type' => 'string',
             'length' => 6,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}